version: '3.3'

services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_DATABASE
      DB_DRIVER: $DB_DRIVER
      DRUSH_OPTIONS_URI: "https://${PROJECT_BASE_URL}"
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
    - ./${PROJECT_NAME}:/var/www/html:cached

  mariadb:
    image: wodby/mariadb:${MARIADB_TAG:-10.5}
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      #MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    networks:
      - default
      - reverse-proxy
    depends_on:
    - php
    ports:
    - 80:80
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
      VIRTUAL_HOST: ${PROJECT_BASE_URL}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${PROJECT_BASE_URL}
    volumes:
    - ./${PROJECT_NAME}:/var/www/html:cached

networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge